### ISSUE TITLE
Pink tiles

### ISSUE THREAD

**Issue by Nautic** [OpenSeaMap/website#4] opened 2014-01-31 15:52 UTC
In the embeddeed chart, there are pink tiles after moving the chart.

The problem exist since 2012-06.

Workaround:
Picture with screenshot of the Fullscreen chart, which links to the Fullscreen chart.

But for charter companies and other who like to use OpenSeaMap in their website, we need a real solution.
See also our HowTo: 
http://wiki.openseamap.org/index.php?title=De:OpenSeaMap_in_Website

**Comment by ehrenfeu** [comment] 2015-01-27 10:24
This is a duplicate of OpenSeaMap/general#1. Closing this one.

**Closed as completed by ehrenfeu** 2015-01-27 10:24 UTC
Labels: bug, duplicate
